# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 468e2c11d412fbf52f606b618c7efa19e0a6cdcd05b77771694ceebbc2f921ba7af03b14428c058077b424cd8878f6a5ba2d33a5681a82a1d1b9a6c15994051a

test:
  secret_key_base: 999c00581d00179a4853b59a440188056dddc682719e44b65a702909833988d4b64415e39c81fe0479df524101581e56077476da1ab578ed3117d6f64487c3f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
